config/routes.rb
require 'sidekiq/web'

Catarse::Application.routes.draw do
  devise_for :users, :controllers => {:registrations => "registrations", :passwords => "passwords"} do
    get "/login" => "devise/sessions#new"
  end

  check_user_admin = lambda { |request| request.env["warden"].authenticate? and request.env['warden'].user.admin }
  constraints check_user_admin do
    mount Sidekiq::Web => '/sidekiq'
  end

  # Non production routes
  if Rails.env == "test"
    match "/fake_login" => "sessions#fake_create", :as => :fake_login
  elsif Rails.env == "development"
    resources :emails, :only => [ :index ]
  end

  ActiveAdmin.routes(self)

  mount CatarsePaypalExpress::Engine => "/", :as => "catarse_paypal_express"
  mount CatarseMoip::Engine => "/", :as => "catarse_moip"

  filter :locale

  root to: 'projects#index'

  match "/reports/financial/:project_id/backers" => "reports#financial_by_project", :as => :backers_financial_report
  match "/reports/location/:project_id/backers" => "reports#location_by_project", :as => :backers_location_report
  match "/reports/users_most_backed" => "reports#users_most_backed", :as => :most_backed_report
  match "/reports/users_most_backed_diff" => "reports#users_most_backed_diff", :as => :most_backed_diff_report
  match "/reports/all_confirmed_backers" => "reports#all_confirmed_backers", :as => :all_confirmed_backers_report
  match "/reports/all_projects_owners" => "reports#all_projects_owner", :as => :all_projects_owner_report
  match "/reports/all_emails" => "reports#all_emails_to_newsletter", :as => :all_emails_to_newsletter

  # Static Pages
  match '/sitemap' => "static#sitemap", :as => :sitemap
  match "/guidelines" => "static#guidelines", :as => :guidelines
  match "/guidelines_tips" => "static#guidelines_tips", :as => :guidelines_tips
  match "/faq" => "static#faq", :as => :faq
  match "/terms" => "static#terms", :as => :terms
  match "/privacy" => "static#privacy", :as => :privacy

  match "/thank_you" => "payment_stream#thank_you", :as => :thank_you
  match "/explore" => "explore#index", :as => :explore
  match "/explore#:quick" => "explore#index", :as => :explore_quick
  match "/credits" => "credits#index", :as => :credits

  post "/auth" => "sessions#auth", :as => :auth
  match "/auth/:provider/callback" => "sessions#create"
  match "/auth/failure" => "sessions#failure"
  match "/logout" => "sessions#destroy", :as => :logout
  resources :unsubscribes, :only => [:index, :create, :destroy]
  resources :posts, only: [:index, :create]
  resources :projects, only: [:index, :new, :create, :show] do
    resources :updates, :only => [:index, :create, :destroy]
    resources :rewards
    resources :backers, controller: 'projects/backers' do
      collection do
        post 'review'
      end
      member do
        put 'checkout'
        post 'update_info'
      end
    end
    collection do
      get 'start'
      post 'send_mail'
      get 'vimeo'
      get 'check_slug'
      get 'cep'
      get 'pending'
      get 'pending_backers'
      get 'thank_you'
      post 'update_attribute_on_the_spot'
    end
    member do
      put 'pay'
      get 'embed'
      get 'video_embed'
    end
  end
  resources :users do
    resources :backers, :only => [:index]
    member do
      get 'projects'
      get 'credits'
    end
    post 'update_attribute_on_the_spot', :on => :collection
  end
  match "/users/:id/request_refund/:back_id" => 'users#request_refund'

  resources :credits, only: [:index] do
    collection do
      get 'buy'
      post 'refund'
    end
  end

  resources :curated_pages do
    collection do
      post 'update_attribute_on_the_spot'
    end
  end
  match "/pages/:permalink" => "curated_pages#show", as: :curated_page

  namespace :adm do
    resources :backers do
      member do
        put 'confirm'
      end
      collection do
        post 'update_attribute_on_the_spot'
      end
    end
    resources :users
  end

  resources :tests

  match "/:permalink" => "projects#show", as: :project_by_slug

end

app/controllers/projects/backers_controller.rb
class Projects::BackersController < ApplicationController
  inherit_resources
  actions :index, :new, :update_info
  before_filter :load_project

  def update_info
    return unless require_login
    @backer = current_user.backs.find params[:id]
    @backer.update_attributes(params[:backer])

    render :json => {:message => 'updated'}
  end

  def index
    @backers = @project.backers.confirmed.order("confirmed_at DESC").page(params[:page]).per(10)
    render :json => @backers.to_json(:can_manage => can?(:manage, @project))
  end

  def new
    return unless require_login
    unless @project.can_back?
      flash[:failure] = t('projects.back.cannot_back')
      return redirect_to :root
    end

    @review_url = ::Configuration[:secure_review_host] ? 
      review_project_backers_url(@project, {:host => ::Configuration[:secure_review_host], :protocol => 'https'}) : 
      review_project_backers_path(@project)

    @title = t('projects.backers.new.title', :name => @project.name)
    @backer = @project.backers.new(:user => current_user)
    empty_reward = Reward.new(:id => 0, :minimum_value => 0, :description => t('projects.backers.new.no_reward'))
    @rewards = [empty_reward] + @project.rewards.order(:minimum_value)
    @reward = @project.rewards.find params[:reward_id] if params[:reward_id]
    @reward = nil if @reward and @reward.sold_out?
    if @reward
      @backer.reward = @reward
      @backer.value = "%0.0f" % @reward.minimum_value
    end
  end

  def review
    return unless require_login

    @title = t('projects.backers.review.title')
    params[:backer][:reward_id] = nil if params[:backer][:reward_id] == '0'
    params[:backer][:user_id] = current_user.id
    @project = Project.find params[:project_id]
    @backer = @project.backers.new(params[:backer])

    unless @backer.save
      flash[:failure] = t('projects.backers.review.error')
      return redirect_to new_project_backer_path(@project)
    end

    session[:thank_you_id] = @project.id
  end

  def checkout
    return unless require_login
    backer = current_user.backs.find params[:id]
    if params[:payment_method_url].present?
      current_user.update_attributes params[:user]
      current_user.reload
      return redirect_to params[:payment_method_url]
    else 
      if backer.credits
        if current_user.credits < backer.value
          flash[:failure] = t('projects.backers.checkout.no_credits')
          return redirect_to new_project_backer_path(backer.project)
        end
        unless backer.confirmed
          current_user.credits = (current_user.credits - backer.value)
          current_user.save
          backer.update_attributes({ payment_method: 'Credits' })
          backer.confirm!
        end
        flash[:success] = t('projects.backers.checkout.success')
        redirect_to thank_you_path
      end
    end
  end



  private

  def load_project
    @project = Project.find params[:project_id]
  end
end

app/controllers/projects_controller.rb
# coding: utf-8
class ProjectsController < ApplicationController
  include ActionView::Helpers::DateHelper

  inherit_resources
  actions :index, :show, :new, :create
  respond_to :html, :except => [:backers]
  respond_to :json, :only => [:index, :show, :backers]
  can_edit_on_the_spot
  skip_before_filter :detect_locale, :only => [:backers]
  before_filter :can_update_on_the_spot?, :only => :update_attribute_on_the_spot
  before_filter :date_format_convert, :only => [:create]

  def date_format_convert
    # TODO localize here and on the datepicker on project_form.js
    params["project"]["expires_at"] = Date.strptime(params["project"]["expires_at"], '%d/%m/%Y')
  end

  def index
    index! do |format|
      format.html do
        @title = t("site.title")
        collection_projects = Project.recommended_for_home
        unless collection_projects.empty?
          if current_user and current_user.recommended_project
            @recommended_project = current_user.recommended_project
            collection_projects = collection_projects.where("id != #{current_user.recommended_project.id}").where("category_id != #{@recommended_project.category_id}")
          end
          @first_project, @second_project, @third_project, @fourth_project = collection_projects.all
        end

        project_ids = collection_projects.map{|p| p.id }
        project_ids << @recommended_project.id if @recommended_project

        @expiring = Project.expiring_for_home(project_ids)
        @recent = Project.recent_for_home(project_ids)

        @blog_posts = Blog.fetch_last_posts.inject([]) do |total,item|
          if total.size < 2
            total << item
          end
          total
        end || []

        calendar = Calendar.new
        @events = Rails.cache.fetch 'calendar', expires_in: 30.minutes do
          calendar.fetch_events_from("catarse.me_237l973l57ir0v6279rhrr1qs0@group.calendar.google.com") || []
        end
        @curated_pages = CuratedPage.visible.order("created_at desc").limit(8)
        @last_tweets = Rails.cache.fetch('last_tweets', :expires_in => 30.minutes) do
          begin
            JSON.parse(Net::HTTP.get(URI("http://api.twitter.com/1/statuses/user_timeline.json?screen_name=#{t('site.twitter')}")))[0..1]
          rescue
            []
          end
        end
        @last_tweets ||= []
      end
      format.json do
        @projects = if params[:search][:name_or_headline_or_about_or_user_name_or_user_address_city_contains]
          Project.visible.unaccent_search( params[:search][:name_or_headline_or_about_or_user_name_or_user_address_city_contains])
        else
          Project.visible.search(params[:search])
        end
        # After the search params we order by ID to avoid ties and therefore duplicate items in pagination
        respond_with(@projects.order('id').page(params[:page]).per(6))
      end
    end
  end

  def start
    return unless require_login
    @title = t('projects.start.title')
  end

  def send_mail
    current_user.update_attributes({ email: params[:contact] }) if current_user.email.nil?
    ProjectsMailer.start_project_email(
      params[:how_much_you_need],
      params[:category],
      params[:about],
      params[:rewards],
      params[:video],
      params[:facebook],
      params[:twitter],
      params[:blog],
      params[:links],
      params[:know_us_via],
      params[:contact],
      current_user,
      "#{I18n.t('site.base_url')}#{user_path(current_user)}").deliver

    # Send project receipt
    Notification.create_notification(:project_received, current_user)

    flash[:success] = t('projects.send_mail.success')
    redirect_to :root
  end

  def new
    return unless require_login
    new! do
      @title = t('projects.new.title')
      @project.rewards.build
    end
  end

  def create
    params[:project][:expires_at] += (23.hours + 59.minutes + 59.seconds) if params[:project][:expires_at]
    if params[:project][:permalink] == ''
      params[:project][:permalink] = nil
    end
    validate_rewards_attributes if params[:project][:rewards_attributes].present?
    create!(:notice => t('projects.create.success'))
    # When it can't create the project the @project doesn't exist and then it causes a record not found
    # because @project.reload *works only with created records*
    unless @project.new_record?
      @project.reload
      @project.update_attributes({ short_url: bitly })
    end
  end

  def show
    begin
      if params[:permalink].present?
        @project = Project.find_by_permalink! params[:permalink]
      elsif resource.permalink
        return redirect_to project_by_slug_path(resource.permalink)
      end

      @project = Project.find params[:id] if params[:id].present?
      if !params[:permalink].present? and @project.permalink.present?
        return redirect_to project_by_slug_url(permalink: @project.permalink)
      end

      show!{
        @title = @project.name
        @rewards = @project.rewards.order(:minimum_value).all
        @backers = @project.backers.confirmed.limit(12).order("confirmed_at DESC").all
        fb_admins_add(@project.user.facebook_id) if @project.user.facebook_id
        @update = @project.updates.where(:id => params[:update_id]).first if params[:update_id].present?
      }
    rescue ActiveRecord::RecordNotFound
      return render_404
    end
  end

  def vimeo
    project = Project.new(:video_url => params[:url])
    if project.vimeo.info
      render :json => project.vimeo.info.to_json
    else
      render :json => {:id => false}.to_json
    end
  end

  def cep
    address = BuscaEndereco.por_cep(params[:cep])
    render :json => {
      :ok => true,
      :street => "#{address[0]} #{address[1]}",
      :neighbourhood => address[2],
      :state => address[3],
      :city => address[4]
    }.to_json
  rescue
    render :json => {:ok => false}.to_json
  end

  def check_slug
    project = Project.where("permalink = ?", params[:permalink])
    render :json => {:available => project.empty?}.to_json
  end

  def embed
    @project = Project.find params[:id]
    @title = @project.name
    render :layout => 'embed'
  end

  def video_embed
    @project = Project.find params[:id]
    @title = @project.name
    render :layout => 'embed'
  end

  def pending
    return unless require_admin
    @title = t('projects.pending.title')
    @search = Project.search(params[:search])
    @projects = @search.order('projects.created_at DESC').page(params[:page])
  end

  def pending_backers
    return unless require_admin
    @title = t('projects.pending_backers.title')
    @search = Backer.search(params[:search])
    @backers = @search.order("created_at DESC").page(params[:page])
  end


  private

  # Just to fix a minor bug,
  # when user submit the project without some rewards.
  def validate_rewards_attributes
    rewards = params[:project][:rewards_attributes]
    rewards.each do |r|
      rewards.delete(r[0]) unless Reward.new(r[1]).valid?
    end
  end

  def bitly
    return unless Rails.env.production?
    require 'net/http'
    res = Net::HTTP.start("api.bit.ly", 80) { |http| http.get("/v3/shorten?login=diogob&apiKey=R_76ee3ab860d76d0d1c1c8e9cc5485ca1&longUrl=#{CGI.escape(project_url(@project))}") }
    data = JSON.parse(res.body)['data']
    data['url'] if data
  end

  def can_update_on_the_spot?
    project_fields = []
    project_admin_fields = ["name", "about", "headline", "can_finish", "expires_at", "user_id", "image_url", "video_url", "visible", "rejected", "recommended", "permalink"]
    backer_admin_fields = ["confirmed", "requested_refund", "refunded", "anonymous", "user_id"]
    reward_fields = []
    reward_admin_fields = ["description"]
    def render_error; render :text => t('require_permission'), :status => 422; end
    return render_error unless current_user
    klass, field, id = params[:id].split('__')
    return render_error unless klass == 'project' or klass == 'backer' or klass == 'reward'
    if klass == 'project'
      return render_error unless project_fields.include?(field) or (current_user.admin and project_admin_fields.include?(field))
      project = Project.find id
      return render_error unless current_user.id == project.user.id or current_user.admin
    elsif klass == 'backer'
      return render_error unless backer_fields.include?(field) or (current_user.admin and backer_admin_fields.include?(field))
      backer = Backer.find id
      return render_error unless current_user.admin or (backer.user == current_user)
    elsif klass == 'reward'
      return render_error unless reward_fields.include?(field) or (current_user.admin and reward_admin_fields.include?(field))
      reward = Reward.find id
      return render_error unless current_user.admin
    end
  end
end

app/views/projects/_back_info.html.haml
#project_back_info
  #back_project= render :partial => 'back_project'
  #rewards= render :partial => 'rewards'
.clear
= javascript_include_tag 'show_project'

app/views/projects/_formatting_tips.html.slim
#show_formatting_tips
  | Quer usar imagens, vídeos, links e formatação? 
  a href="#" Clique aqui
  | .
#formatting_tips
  h3 Saiba como você pode formatar seu comentário
  ul
    li
      | Se você colar a URL de uma imagem ou de um vídeo do Vimeo ou do YouTube, eles irão aparecer no comentário. Experimente!
    li
      | Ao colar uma URL qualquer, ela virará um link. Por exemplo, http://catarse.me virará 
      a href="http://catarse.me" target="_blank" http://catarse.me
      | .
    li
      | Se você quiser colocar um texto no link, basta usar o seguinte formato: 
      strong "texto que você quer":http://sua.url
      | . Por exemplo, "Catarse":http://catarse.me virará 
      a href="http://catarse.me" target="_blank" Catarse
      | .
    li
      | Você pode usar 
      strong negrito 
      | adicionando um asterisco (*) antes e depois do texto que você quer formatar. Por exemplo, *meu texto em negrito* irá aparecer como 
      strong meu texto em negrito
      | .
    li
      | Você pode usar 
      em itálico 
      | adicionando um underline (_) antes e depois do texto que você quer formatar. Por exemplo, _meu texto em itálico_ irá aparecer como 
      em meu texto em itálico
      | .

app/views/projects/_how_it_works.en.html.haml
Catarse works like this: you submit your project, tell us
%strong how much do you need
and a
%strong deadline
to reach this goal. Then you promote the project and people can opt to
%strong back with any amount
starting from R$10 and
%strong receive rewards
for that! If until the chosen deadline you have reached the amount you need, you get the money. Otherwise, everybody receives the money back. Simple like that.
#show_tips
  %a{:href => '#'} See more tips on how Catarse works

app/views/projects/_project.html.slim
div class="curated_project #{(defined?(has_comments) ? :compost_project : '')}"
  = render 'projects/box', project: project, custom_class: (custom_class if defined?(custom_class))
  - if defined?(has_comments)
    .project_comment
      h3= "#{(defined?(comments_title) ? comments_title : project.category.name)}"
      p= "#{project.home_page_comment}"
  - if defined?(project_curated_page) and project_curated_page.count > 0 and project_curated_page.first.description.present?
    .project_curator_description
      == project_curated_page.first.description_html

app/views/projects/_recommended_header.html.slim
#recommended_header
  .resume_about
    h1= t('projects.index_header.title')
    h4= t('projects.index_header.subtitle_html')
  .project_info
    - if has_institutional_videos?
      == render 'layouts/institutional_video_header'
    - elsif current_user
      - if @recommended_project
        = render :partial => "project_header", :locals => {:title => t('projects.recommended_header.sugest_for_you'), :project => @recommended_project} if @recommended_project
      - else
        = render :partial => "project_header", :locals => {:title => t('projects.recommended_header.highlight_project'), :project => @fourth_project} if @fourth_project
    - else
      = render :partial => "project_header", :locals => {:title => t('projects.recommended_header.highlight_project'), :project => @fourth_project} if @fourth_project
  .clearfix

app/views/projects/embed.html.haml
#embed
  = render :partial => 'box', :locals => { :project => @project, :embed_link => true }

app/views/projects/guidelines.html.haml
= content_for :content_header do
  %h1= t('.title')
  %h2= t('.subtitle')
#how_it_works= render 'how_it_works'
#more_tips.hide= render 'more_tips'
= render 'guidelines_text'
= form_tag(start_projects_path, :method => :get, :id => 'guidelines_form') do
  %fieldset
    = check_box_tag 'accept'
    = label_tag 'accept', t('.accept')
  %fieldset
    = submit_tag t('.submit'), :disabled => true
= javascript_include_tag 'guidelines'

app/views/projects/new.html.slim
#page_content
  .container
    .start_content
      .title
        h1= t('.title')
        h2= t('.subtitle')
        p= t('.introduction_html')
      .bootstrap-form
        = render 'form'
    .clearfix

app/views/projects/pending.html.haml
#page_content
  .container
    .project_content
      .title
        %h1= t('.title')
      #pending_projects
        .bootstrap-form
          = form_for @search, :url => pending_projects_path, class: 'form-horizontal' do |f|
            %fieldset
              .input
                = f.label :id_equals, t('.id')
                = f.text_field :id_equals
              .input
                = f.label :name_contains, t('.name')
                = f.text_field :name_contains
              .input
                = f.label :user_name_contains, t('.user')
                = f.text_field :user_name_contains
              .bootstrap-twitter
                .input.submit
                  = f.submit t('.submit'), class: 'btn btn-success'
            %fieldset
              .input.check
                = f.check_box :visible_is_true
                = f.label :visible_is_true, t('.visible')
              .input.check
                = f.check_box :rejected_is_true
                = f.label :rejected_is_true, t('.rejected')
              .input.check
                = f.check_box :recommended_is_true
                = f.label :recommended_is_true, t('.recommended')
              .input.check
                = f.check_box :home_page_is_true
                = f.label :home_page_is_true, t('.home_page')
              .input.check
                = f.check_box :can_finish_is_true
                = f.label :can_finish_is_true, t('.can_finish')
              .input.check
                = f.check_box :finished_is_true
                = f.label :finished_is_true, t('.finished')
              .input.total_results
                #total_results
                  = pluralize_without_number @search.count, t('found_singular'), t('found_plural')
                  %strong= @search.count
                  = pluralize_without_number @search.count, t('activerecord.models.project').downcase
        .clearfix
        = paginate @projects
        .clear
        - if @projects.empty?
          = t('.no_projects')
        - else
          .bootstrap-twitter
            %table.table.table-striped
              %thead
                %tr
                  %th= t('.id')
                  %th= t('.project')
                  %th= t('.user')
                  %th= t('.slug')
                  %th= t('.visible')
                  %th= t('.rejected')
                  %th= t('.recommended')
                  %th= t('.home_page')
                  %th= t('.order')
                  %th= t('.can_finish')
                  %th= t('.finished')
              %tbody
                - @projects.each do |project|
                  %tr{ :class => cycle("even", "odd") }
                    %td= project.id
                    %td{ :title => project.name }
                      = link_to project_path(project) do
                        = image_tag project.display_image, class: 'project_img'
                    %td{ :title => project.user.display_name }
                      = link_to user_path(project.user) do
                        = image_tag project.user.display_image, class: 'user_img'
                    %td= on_the_spot_edit project, :permalink, :tooltip => '-'
                    %td= check_box_tag "project__visible__#{project.id}", '1', project.visible
                    %td= check_box_tag "project__rejected__#{project.id}", '1', project.rejected
                    %td= check_box_tag "project__recommended__#{project.id}", '1', project.recommended
                    %td= check_box_tag "project__home_page__#{project.id}", '1', project.home_page
                    %td= on_the_spot_edit project, :order, :tooltip => '-'
                    %td= check_box_tag "project__can_finish__#{project.id}", '1', project.can_finish
                    %td= (project.finished ? t('yes') : t('no'))
        = paginate @projects
    .clearfix

app/views/projects/pending_backers.html.haml
#page_content
  .container
    .project_content
      .title
        %h1= t('.title')
        %h2
          %strong= @total_backers
          = t('.total_backers')
          ·
          %strong= @total_backs
          = t('.total_backs')
          ·
          %strong= number_to_currency @total_backed, :unit => 'R$', :precision => 0, :delimiter => '.'
          = t('.total_backed')
          ·
          %strong= @total_users
          = t('.total_users')

      #pending_backers
        .bootstrap-form
          = form_for @search, :url => pending_backers_projects_path, class: 'form-horizontal' do |f|
            %fieldset
              .input
                = f.label :id_equals, t('.id')
                = f.text_field :id_equals, class: 'input-small'
              .input
                = f.label :key_equals, t('.key')
                = f.text_field :key_equals
              .input
                = f.label :project_name_contains, t('.project')
                = f.text_field :project_name_contains
              .input
                = f.label :user_name_contains, t('.user')
                = f.text_field :user_name_contains
              .bootstrap-twitter
                .input.submit
                  = f.submit t('.submit'), class: 'btn btn-success'
            %fieldset
              .input.check
                = f.check_box :confirmed_is_true
                = f.label :confirmed_is_true, t('.confirmed')
              .input.check
                = f.check_box :credits_is_true
                = f.label :credits_is_true, t('.credits')
              .input.check
                = f.check_box :requested_refund_is_true
                = f.label :requested_refund_is_true, t('.requested_refund')
              .input.check
                = f.check_box :refunded_is_true
                = f.label :refunded_is_true, t('.refunded')
              .input.total_results
                #total_results
                  = pluralize_without_number @search.count, t('found_singular'), t('found_plural')
                  %strong= @search.count
                  = pluralize_without_number(@search.count, t('backer_singular'), t('backer_plural')).downcase
        .clearfix
        = paginate @backers
        - if @backers.empty?
          = t('.no_backers')
        - else
          .bootstrap-twitter
            %table.table.table-striped
              %thead
                %tr
                  %th= t('.id')
                  %th= t('.project')
                  %th= t('.user')
                  %th= t('.value')
                  %th= t('.reward')
                  %th= t('.key')
                  %th= t('.confirmed')
                  %th= t('.anonymous')
                  %th= t('.credits')
                  %th= t('.requested_refund')
                  %th= t('.refunded')
              %tbody
                - @backers.each do |backer|
                  %tr{ :id => backer.id, :class => cycle("even", "odd") }
                    %td= backer.id
                    %td{ :title => backer.project.name }
                      = link_to project_path(backer.project) do
                        = image_tag backer.project.display_image, class: 'project_img'
                    %td{ :title => backer.user.display_name }
                      = link_to user_path(backer.user) do
                        = image_tag backer.user.display_image, class: 'user_img'
                      .user_id= on_the_spot_edit backer, :user_id
                    %td= backer.display_value
                    %td{ :title => ("#{backer.reward.display_minimum} - #{backer.reward.description}" if backer.reward) }
                      - if backer.reward
                        = backer.reward.display_minimum
                      - else
                        \-
                    %td.key= backer.key
                    %td= check_box_tag "confirmed__#{backer.id}", '1', backer.confirmed
                    %td= check_box_tag "anonymous__#{backer.id}", '1', backer.anonymous
                    %td= (backer.credits ? t('yes') : t('no'))
                    %td= (backer.requested_refund ? t('yes') : t('no'))
                    %td= check_box_tag "refunded__#{backer.id}", '1', backer.refunded
        = paginate @backers
    .clearfix
      

app/views/projects/review.html.haml
= content_for :content_header do
  %h1= t('.title')
  %h2= t('.subtitle')
#project_review
  = image_tag @project.display_image, :id => 'project_image'
  %h1= t('.you_are_about_html', :link => link_to(@project.name, project_path(@project)))
  .clear
  #review_text
    - if @backer.reward
      = t('.review_with_reward_html', :value => @backer.display_value, :reward => @backer.reward.description)
    - else
      = t('.review_without_reward_html', :value => @backer.display_value)
  - if @backer.credits
    #credits_notice= t('.credits_notice_html', :credits => number_to_currency((current_user.credits - @backer.value), :unit => 'R$', :precision => 0, :delimiter => '.'))
  - else
    #international_payment
      %h1
        = t('.international.title')
        %a#international_link{ :href => '#' }
          = t('click_here')
      #international_expanded.hide
        %h1= t('.international.description')
        .international_important= t('.international.important_html')
        = form_tag(pay_paypal_path(@backer), :method => :get) do
          %fieldset
            = check_box_tag 'accept_international'
            = label_tag 'accept_international', t('accept_terms_html', :link => link_to(t('terms'), terms_path, :target => :_blank)), :class => 'inline'
          %fieldset
            = submit_tag t('.international.submit'), :disabled => true, :id => 'international_submit'
  = semantic_form_for current_user, :url => pay_project_path(@backer.project), :html => { :id => 'review_form' } do |form|
    = hidden_field_tag 'backer_id', @backer.id
    = hidden_field_tag 'backer_credits', @backer.credits
    - unless @backer.credits
      = form.inputs do
        = form.input :full_name, :required => true, :as => :string
        = form.input :email, :required => true, :as => :string
        = form.input :address_zip_code, :required => true, :as => :string
        = form.input :address_street, :required => true, :as => :string
        = form.input :address_number, :required => true, :as => :string
        = form.input :address_complement, :required => false, :as => :string
        = form.input :address_neighbourhood, :required => true, :as => :string
        = form.input :address_city, :required => true, :as => :string
        = form.input :address_state, :required => true, :as => :select, :collection => State.array
        = form.input :phone_number, :required => true, :as => :string, :input_html => {:autocomplete => 'off'}
    .submit
      %fieldset
        = check_box_tag 'accept'
        = label_tag 'accept', t('accept_terms_html', :link => link_to(t('terms'), terms_path, :target => :_blank)), :class => 'inline'
      = form.buttons do
        = form.commit_button (@backer.credits ? t('.submit.credits') : t('.submit.moip')), :button_html => {:disabled => true}
= javascript_include_tag 'jquery.maskedinput-1.2.2.min'
= javascript_include_tag 'review'