config/routes.rb
require 'sidekiq/web'

Catarse::Application.routes.draw do
  devise_for :users, :controllers => {:registrations => "registrations", :passwords => "passwords"} do
    get "/login" => "devise/sessions#new"
  end

  check_user_admin = lambda { |request| request.env["warden"].authenticate? and request.env['warden'].user.admin }
  constraints check_user_admin do
    mount Sidekiq::Web => '/sidekiq'
  end

  # Non production routes
  if Rails.env == "test"
    match "/fake_login" => "sessions#fake_create", :as => :fake_login
  elsif Rails.env == "development"
    resources :emails, :only => [ :index ]
  end

  ActiveAdmin.routes(self)

  mount CatarsePaypalExpress::Engine => "/", :as => "catarse_paypal_express"
  mount CatarseMoip::Engine => "/", :as => "catarse_moip"

  filter :locale

  root to: 'projects#index'

  match "/reports/financial/:project_id/backers" => "reports#financial_by_project", :as => :backers_financial_report
  match "/reports/location/:project_id/backers" => "reports#location_by_project", :as => :backers_location_report
  match "/reports/users_most_backed" => "reports#users_most_backed", :as => :most_backed_report
  match "/reports/users_most_backed_diff" => "reports#users_most_backed_diff", :as => :most_backed_diff_report
  match "/reports/all_confirmed_backers" => "reports#all_confirmed_backers", :as => :all_confirmed_backers_report
  match "/reports/all_projects_owners" => "reports#all_projects_owner", :as => :all_projects_owner_report
  match "/reports/all_emails" => "reports#all_emails_to_newsletter", :as => :all_emails_to_newsletter

  # Static Pages
  match '/sitemap' => "static#sitemap", :as => :sitemap
  match "/guidelines" => "static#guidelines", :as => :guidelines
  match "/guidelines_tips" => "static#guidelines_tips", :as => :guidelines_tips
  match "/faq" => "static#faq", :as => :faq
  match "/terms" => "static#terms", :as => :terms
  match "/privacy" => "static#privacy", :as => :privacy

  match "/thank_you" => "payment_stream#thank_you", :as => :thank_you
  match "/explore" => "explore#index", :as => :explore
  match "/explore#:quick" => "explore#index", :as => :explore_quick
  match "/credits" => "credits#index", :as => :credits

  post "/auth" => "sessions#auth", :as => :auth
  match "/auth/:provider/callback" => "sessions#create"
  match "/auth/failure" => "sessions#failure"
  match "/logout" => "sessions#destroy", :as => :logout
  resources :unsubscribes, :only => [:index, :create, :destroy]
  resources :posts, only: [:index, :create]
  resources :projects, only: [:index, :new, :create, :show] do
    resources :updates, :only => [:index, :create, :destroy]
    resources :rewards
    resources :backers, controller: 'projects/backers' do
      collection do
        post 'review'
      end
      member do
        put 'checkout'
        post 'update_info'
      end
    end
    collection do
      get 'start'
      post 'send_mail'
      get 'vimeo'
      get 'check_slug'
      get 'cep'
      get 'pending'
      get 'pending_backers'
      get 'thank_you'
      post 'update_attribute_on_the_spot'
    end
    member do
      put 'pay'
      get 'embed'
      get 'video_embed'
    end
  end
  resources :users do
    resources :backers, :only => [:index]
    member do
      get 'projects'
      get 'credits'
    end
    post 'update_attribute_on_the_spot', :on => :collection
  end
  match "/users/:id/request_refund/:back_id" => 'users#request_refund'

  resources :credits, only: [:index] do
    collection do
      get 'buy'
      post 'refund'
    end
  end

  resources :curated_pages do
    collection do
      post 'update_attribute_on_the_spot'
    end
  end
  match "/pages/:permalink" => "curated_pages#show", as: :curated_page

  namespace :adm do
    resources :backers do
      member do
        put 'confirm'
      end
      collection do
        post 'update_attribute_on_the_spot'
      end
    end
    resources :users
  end

  resources :tests

  match "/:permalink" => "projects#show", as: :project_by_slug

end

app/models/backer.rb
# coding: utf-8
class Backer < ActiveRecord::Base
  include ActionView::Helpers::NumberHelper
  include ActionView::Helpers::DateHelper
  belongs_to :project
  belongs_to :user
  belongs_to :reward
  has_many :payment_notifications
  validates_presence_of :project, :user, :value
  validates_numericality_of :value, :greater_than_or_equal_to => 10.00
  validate :reward_must_be_from_project
  scope :anonymous, where(:anonymous => true)
  scope :not_anonymous, where(:anonymous => false)
  scope :confirmed, where(:confirmed => true)
  scope :not_confirmed, where(:confirmed => false)
  scope :pending, where(:confirmed => false)

  # Backers already refunded or with requested_refund should appear so that the user can see their status on the refunds list
  scope :can_refund, ->{ where("confirmed AND EXISTS(SELECT true FROM projects p WHERE p.id = backers.project_id AND finished AND NOT successful) AND date(current_timestamp) <= date(created_at + interval '180 days')") }
  attr_protected :confirmed

  def price_in_cents
    (self.value * 100).round
  end

  def refund!
    self.refunded = true
    self.save
  end

  def refund_deadline
    created_at + 180.days
  end

  def confirm!
    self.confirmed = true
    self.save
  end

  def can_refund?
    confirmed? && created_at >= (Date.today - 180.days) && project.finished? && !project.successful?
  end

  def reward_must_be_from_project
    return unless reward
    errors.add(:reward, I18n.t('backer.reward_must_be_from_project')) unless reward.project == project
  end

  validate :value_must_be_at_least_rewards_value

  def value_must_be_at_least_rewards_value
    return unless reward
    errors.add(:value, I18n.t('backer.value_must_be_at_least_rewards_value', :minimum_value => reward.display_minimum)) unless value >= reward.minimum_value
  end

  validate :should_not_back_if_maximum_backers_been_reached, :on => :create

  def should_not_back_if_maximum_backers_been_reached
    return unless reward and reward.maximum_backers and reward.maximum_backers > 0
    errors.add(:reward, I18n.t('backer.should_not_back_if_maximum_backers_been_reached')) unless reward.backers.confirmed.count < reward.maximum_backers
  end

  def display_value
    number_to_currency value, :unit => "R$", :precision => 0, :delimiter => '.'
  end

  def display_confirmed_at
    I18n.l(confirmed_at.to_date) if confirmed_at
  end

  def platform_fee(fee=7.5)
    (value.to_f * fee)/100
  end

  def display_platform_fee(fee=7.5)
    number_to_currency platform_fee(fee), :unit => "R$", :precision => 2, :delimiter => '.'
  end

  def moip_value
    "%0.0f" % (value * 100)
  end

  def cancel_refund_request!
    raise I18n.t('credits.cannot_cancel_refund_reques') unless self.requested_refund
    raise I18n.t('credits.refund.refunded') if self.refunded
    raise I18n.t('credits.refund.no_credits') unless self.user.credits >= self.value
    self.update_attributes({ requested_refund: false })
    self.user.update_attributes({ credits: (self.user.credits + self.value) })
  end

  def as_json(options={})
    json_attributes = {
      :id => id,
      :anonymous => anonymous,
      :confirmed => confirmed,
      :confirmed_at => display_confirmed_at,
      :value => display_value,
      :user => user.as_json(options.merge(:anonymous => anonymous)),
      :display_value => nil,
      :reward => nil
    }
    if options and options[:can_manage]
      json_attributes.merge!({
        :display_value => display_value,
        :reward => reward
      })
    end
    if options and options[:include_project]
      json_attributes.merge!({:project => project})
    end
    if options and options[:include_reward]
      json_attributes.merge!({:reward => reward})
    end
    json_attributes
  end

  #==== Used on before and after callbacks

  def define_key
    self.update_attributes({ key: Digest::MD5.new.update("#{self.id}###{self.created_at}###{Kernel.rand}").to_s })
  end

  def define_payment_method
    self.update_attributes({ payment_method: 'MoIP' })
  end
end

app/controllers/adm/backers_controller.rb
class Adm::BackersController < Adm::BaseController
  inherit_resources
  can_edit_on_the_spot
  menu I18n.t("adm.backers.index.menu") => Rails.application.routes.url_helpers.adm_backers_path
  before_filter :set_title
  before_filter :can_update_on_the_spot?, :only => :update_attribute_on_the_spot

  def confirm
    @backer = Backer.find params[:id]
    @backer.confirm!
    flash[:notice] = I18n.t('adm.backers.messages.successful.confirm')
    redirect_to adm_backers_path
  end

  protected
  def can_update_on_the_spot?
    project_fields = []
    backer_fields = []
    project_admin_fields = ["name", "about", "headline", "can_finish", "expires_at", "user_id", "image_url", "video_url", "visible", "rejected", "recommended", "permalink"]
    backer_admin_fields = ["confirmed", "requested_refund", "refunded", "anonymous", "user_id"]
    reward_fields = []
    reward_admin_fields = ["description"]
    def render_error; render :text => t('require_permission'), :status => 422; end
    return render_error unless current_user
    klass, field, id = params[:id].split('__')
    return render_error unless klass == 'project' or klass == 'backer' or klass == 'reward'
    if klass == 'project'
      return render_error unless project_fields.include?(field) or (current_user.admin and project_admin_fields.include?(field))
      project = Project.find id
      return render_error unless current_user.id == project.user.id or current_user.admin
    elsif klass == 'backer'
      return render_error unless backer_fields.include?(field) or (current_user.admin and backer_admin_fields.include?(field))
      backer = Backer.find id
      return render_error unless current_user.admin or (backer.user == current_user)
    elsif klass == 'reward'
      return render_error unless reward_fields.include?(field) or (current_user.admin and reward_admin_fields.include?(field))
      reward = Reward.find id
      return render_error unless current_user.admin
    end
  end

  def set_title
    @title = t("adm.backers.index.title")
  end

  def collection
    @search = Backer.search(params[:search])
    @backers = @search.order("created_at DESC").page(params[:page])
  end
end

app/controllers/backers_controller.rb
class BackersController < ApplicationController
  inherit_resources
  defaults :resource_class => Backer, :collection_name => 'backs', :instance_name => 'back'
  belongs_to :user
  actions :index
  respond_to :json, :only => [:index]

  def index
    index! do |format|
      format.json{ return render :json => @backs.to_json({:include_project => true, :can_manage => (current_user == @user)}) }
      format.html{ return render :nothing => true, :status => 404 }
    end
  end

  protected
  def collection
    @backs = end_of_association_chain.confirmed.order("confirmed_at DESC")
    @backs = @backs.not_anonymous unless @user == current_user or (current_user and current_user.admin)
    @backs = @backs.page(params[:page]).per(10)
  end
end

app/controllers/projects/backers_controller.rb
class Projects::BackersController < ApplicationController
  inherit_resources
  actions :index, :new, :update_info
  before_filter :load_project

  def update_info
    return unless require_login
    @backer = current_user.backs.find params[:id]
    @backer.update_attributes(params[:backer])

    render :json => {:message => 'updated'}
  end

  def index
    @backers = @project.backers.confirmed.order("confirmed_at DESC").page(params[:page]).per(10)
    render :json => @backers.to_json(:can_manage => can?(:manage, @project))
  end

  def new
    return unless require_login
    unless @project.can_back?
      flash[:failure] = t('projects.back.cannot_back')
      return redirect_to :root
    end

    @review_url = ::Configuration[:secure_review_host] ? 
      review_project_backers_url(@project, {:host => ::Configuration[:secure_review_host], :protocol => 'https'}) : 
      review_project_backers_path(@project)

    @title = t('projects.backers.new.title', :name => @project.name)
    @backer = @project.backers.new(:user => current_user)
    empty_reward = Reward.new(:id => 0, :minimum_value => 0, :description => t('projects.backers.new.no_reward'))
    @rewards = [empty_reward] + @project.rewards.order(:minimum_value)
    @reward = @project.rewards.find params[:reward_id] if params[:reward_id]
    @reward = nil if @reward and @reward.sold_out?
    if @reward
      @backer.reward = @reward
      @backer.value = "%0.0f" % @reward.minimum_value
    end
  end

  def review
    return unless require_login

    @title = t('projects.backers.review.title')
    params[:backer][:reward_id] = nil if params[:backer][:reward_id] == '0'
    params[:backer][:user_id] = current_user.id
    @project = Project.find params[:project_id]
    @backer = @project.backers.new(params[:backer])

    unless @backer.save
      flash[:failure] = t('projects.backers.review.error')
      return redirect_to new_project_backer_path(@project)
    end

    session[:thank_you_id] = @project.id
  end

  def checkout
    return unless require_login
    backer = current_user.backs.find params[:id]
    if params[:payment_method_url].present?
      current_user.update_attributes params[:user]
      current_user.reload
      return redirect_to params[:payment_method_url]
    else 
      if backer.credits
        if current_user.credits < backer.value
          flash[:failure] = t('projects.backers.checkout.no_credits')
          return redirect_to new_project_backer_path(backer.project)
        end
        unless backer.confirmed
          current_user.credits = (current_user.credits - backer.value)
          current_user.save
          backer.update_attributes({ payment_method: 'Credits' })
          backer.confirm!
        end
        flash[:success] = t('projects.backers.checkout.success')
        redirect_to thank_you_path
      end
    end
  end



  private

  def load_project
    @project = Project.find params[:project_id]
  end
end

app/views/projects/backers/_anonymous_warning.en.html.slim
strong Are you sure you want your back to be anonymous? 
| Leaving your back public gives you a better reputation and count points on our ranking of backers.
br
br
| Besides that, the amount you backed will never be disclosed to no one but the project owner (who will always know who you are), even if your back is public.

app/views/projects/backers/_anonymous_warning.pt.html.slim
strong Você tem certeza que quer que seu apoio seja anônimo? 
| Deixar seu apoio público aumenta sua reputação e conta pontos para o nosso ranking de apoiadores.
br
br
| Além disso, o valor do seu apoio não será divulgado para ninguém além do dono do projeto. Somente o proponente terá acesso a essa informação, independente se o seu investimento seja público ou anônimo.

app/views/projects/backers/_back_text.en.html.slim
h2 I want to back, how do I do it?
h3 How do I back this project?
p First, chose the value and reward you wish. Then we will redirect you to #{link_to "MoIP", "http://www.moip.com.br/", :target => :_blank} so you can proceed with the payment.
h3 When is the payment made and confirmed?
p Shortly after MoIP confirms the transaction. After that, if the project doesn't reach #{@project.display_goal} until #{@project.display_expires_at}, you will receive your money back as credits on Catarse.
h3 Oh, so I receive my money back if the project doesn't succeed?
p Yes! You receive 100% back as credits to back other projects on Catarse.
h3 What if I don't want to use the credits on Catarse?
p No problem. Just go to #{link_to t('credits.title'), credits_path, :target => :_blank}, up until 180 days after your payment, and request a refund. If you payed with credit card, the refund will be received in your next bill. If you payed with debit or transfer, the only way to receive the refund is to open an account on MoIP. This way we transfer you the value from our account to yours and, from there, you transfer to your bank account. No matter what way you chose, you wont have to pay anything.
h3 If the project is successful, how do I receive my reward?
p When your reward is ready, #{link_to @project.user.display_name, user_path(@project.user)} will get in touch with you to arrange the delivery.

app/views/projects/backers/_back_text.pt.html.slim
h2 Quero apoiar, e agora?
h3 Como eu apoio este projeto?
p Primeiro, escolha o valor e a recompensa desejados. Depois nós te redirecionaremos para o #{link_to "MoIP", "http://www.moip.com.br/", :target => :_blank} para que você efetue o pagamento.
h3 Quando o pagamento é efetivado?
p Assim que o MoIP confirmar a transação. Depois, caso o projeto não atinja #{@project.display_goal} até #{@project.display_expires_at}, você receberá seu dinheiro de volta na forma de créditos no Catarse.
h3 Então eu recebo meu dinheiro de volta se o projeto não sair?
p Sim! Você recebe de volta 100% do que pagou na forma de créditos para apoiar outros projetos do Catarse.
h3 E se eu não quiser usar os créditos no Catarse?
p Sem problemas. É só entrar em #{link_to t('credits.title'), credits_path, :target => :_blank}, até 180 dias após seu apoio, e solicitar um estorno. Caso tenha pago com cartão de crédito, o estorno será feito na sua próxima fatura. Se pagou com débito em conta ou boleto bancário, a única maneira de fazer o estorno é você abrir uma conta no MoIP. Aí a gente transfere o valor da nossa conta para a sua e, de lá, você transfere para sua conta no banco. Independente do jeito que preferir, você não terá nenhuma despesa.
h3 Se o projeto for financiado, como eu recebo minha recompensa?
p Quando sua recompensa estiver pronta, #{link_to @project.user.display_name, user_path(@project.user)} vai entrar em contato com você para combinar a entrega.

app/views/projects/backers/new.html.haml
#page_content
  .container
    .backer_content
      .title
        %h1= t('.header.title')
        %h2= t('.header.subtitle')
      #back_options.bootstrap-form
        = semantic_form_for @backer, :url => review_project_backers_path(@project), :html => { :id => 'backer_form' } do |form|
          = form.inputs do
            = hidden_field_tag 'credits', ("%0.0f" % current_user.credits)
            = form.input :value, :required => false, :as => :string
            - if current_user.credits >= 10
              .bootstrap-alert
                .alert.alert-info
                  = form.input :credits, :hint => t('formtastic.hints.backer.credits', :credits => current_user.display_credits).html_safe
            - @rewards[0].id = 0
            %script
              var rewards = new Array()
              - @rewards.each do |reward|
                rewards[#{reward.id || 0}] = #{reward.minimum_value}
            = form.input :reward, :as => :radio, :collection => @rewards
            = form.input :anonymous
            #anonymous_warning.important.hide
              .bootstrap-alert
                .alert
                  = render 'anonymous_warning'
          = form.buttons do
            .bootstrap-twitter
              = form.commit_button t('.submit'), :button_html => {:disabled => true, :class => 'btn btn-primary btn-large'}
      #back_info
        = image_tag @project.display_image, alt: @project.name, class: 'project_image', width: 280
        #project_info
          .project_name= link_to @project.name, project_path(@project)
          .project_owner por #{link_to @project.user.display_name, user_path(@project.user)}
          .project_expires_at #{@project.time_to_go[:time]} #{@project.time_to_go[:unit]} #{pluralize_without_number(@project.time_to_go[:time], t('remaining_singular'), t('remaining_plural'))}
        .clearfix
        .back_faq
          = render 'back_text'
      .clearfix
    .clearfix

app/views/projects/backers/new.html.slim
#page_content
  .container
    .backer_content
      .title
        h1= t('.header.title')
        h2= t('.header.subtitle')
      #back_options.bootstrap-form 
        = semantic_form_for @backer, :url => @review_url, :html => { :id => 'backer_form' } do |form|
          = form.inputs do
            = hidden_field_tag 'credits', ("%0.0f" % current_user.credits)   
            = form.input :value, :required => false, :as => :string
            .simbol
              p R$
            - if current_user.credits >= 10
              .bootstrap-alert
                .alert.alert-info
                  = form.input :credits, :hint => t('formtastic.hints.backer.credits', :credits => current_user.display_credits).html_safe
              .clearfix
            - @rewards[0].id = 0
            script
              |var rewards = new Array();
              - @rewards.each do |reward|
                |rewards[#{reward.id || 0}] = #{reward.minimum_value};
            = form.input :reward, :as => :radio, :collection => @rewards
            = form.input :anonymous
            #anonymous_warning.important.hide
              .bootstrap-alert
                .alert
                  = render 'anonymous_warning'       
          = form.actions do
            .bootstrap-twitter
              = form.submit t('.submit'), :disabled => true, :class => 'btn btn-primary btn-large', :id => "backer_submit"
      #back_info
        #project_info
          .project_name= link_to @project.name, project_path(@project)
          = image_tag @project.display_image, alt: @project.name, class: 'project_image', width: 280
          .project_owner por #{link_to @project.user.display_name, user_path(@project.user)}
          .project_expires_at #{@project.time_to_go[:time]} #{@project.time_to_go[:unit]} #{pluralize_without_number(@project.time_to_go[:time], t('remaining_singular'), t('remaining_plural'))}
        .clearfix
        .back_faq
          = render 'back_text'
      .clearfix
    .clearfix

app/views/projects/backers/review.html.haml
#page_content
  .container
    #project_review
      .project_info
        = image_tag @project.display_image, :id => 'project_image', :alt => @project.name, :width => '250px'
        %h1= t('.you_are_about_html', :link => link_to(@project.name, project_path(@project)))
        #review_text
          - if @backer.reward
            = t('.review_with_reward_html', :value => @backer.display_value, :reward => @backer.reward.description)
          - else
            = t('.review_without_reward_html', :value => @backer.display_value)
      .clearfix
      .title
        %h1= t('.title')
        %h2= t('.subtitle')
      .clearfix
      - if @backer.credits
        #back_with_credits
          .bootstrap-alert
            .alert
              #credits_notice= t('.credits_notice_html', :credits => number_to_currency((current_user.credits - @backer.value), :unit => 'R$', :precision => 0, :delimiter => '.'))
      - else
      .bootstrap-form
        = semantic_form_for current_user, :url => checkout_project_backer_path(@backer.project, @backer), :html => { :id => 'review_form', :class => "form-horizontal #{('dont_align' if @backer.credits)}" } do |form|
          = hidden_field_tag 'backer_id', @backer.id
          = hidden_field_tag 'backer_credits', @backer.credits
          - unless @backer.credits
            = form.inputs do
              = form.input :full_name, :required => true, :as => :string
              = form.input :cpf, :as => :string, :input_html => {:autocomplete => 'off'}
              = form.input :email, :required => true, :as => :string
              = form.input :address_street, :as => :string
              = form.input :address_number, :as => :string
              = form.input :address_complement, :required => false, :as => :string
              = form.input :address_neighbourhood, :as => :string
              = form.input :address_zip_code, :as => :string, :input_html => {:autocomplete => 'off'}
              = form.input :address_city, :as => :string
              = form.input :address_state, :as => :select, :collection => State.array
              = form.input :phone_number, :as => :string, :input_html => {:autocomplete => 'off'}
          .submit
            %fieldset.accept_terms
              = check_box_tag 'accept'
              = label_tag 'accept', t('accept_terms_html', :link => link_to(t('terms'), terms_path, :target => :_blank)), :class => 'inline'
            - if @backer.credits
              = form.actions do
                .bootstrap-twitter
                  = form.submit (@backer.credits ? t('.submit.credits') : t('.submit.moip')), :disabled => true, :class => 'btn', :id => 'user_submit'
          #payment.hide
            .title
              %h1= t('.choose_payment')
            .choose_payment
              .cc
                = link_to pay_paypal_path(@backer), :method => :get do
                  = image_tag 'catarse/cc_icon.png'
                  %span= t('.choose_credit_card')
                .clearfix
              .or
                %span= t('or')
              .boleto
                = link_to checkout_project_backer_path(@backer.project, @backer), :method => :put do
                  = image_tag 'catarse/boleto_icon.png'
                  %span= t('.choose_boleto')

    .clearfix

app/views/projects/backers/review.html.slim
#page_content
  .container
    #project_review
      .project_info
        = image_tag @project.display_image, :id => 'project_image', :alt => @project.name, :width => '250px'
        h1= t('.you_are_about_html', :link => link_to(@project.name, project_path(@project)))
        #review_text
          - if @backer.reward
            .review_content
              = t('.review_with_reward_html', :value => @backer.display_value)
            .reward
              = @backer.reward.description
          - else
            .review_content
              = t('.review_without_reward_html', :value => @backer.display_value)
      .clearfix
      .title
        h1= t('.title')
        h2= t('.subtitle')
      .clearfix
      - if @backer.credits
        #back_with_credits
          .bootstrap-alert
            .alert
              #credits_notice= t('.credits_notice_html', :credits => number_to_currency((current_user.credits - @backer.value), :unit => 'R$', :precision => 0, :delimiter => '.'))
      .bootstrap-form
        = semantic_form_for current_user, :url => checkout_project_backer_path(@backer.project, @backer), :html => { :id => 'review_form', :class => "form-horizontal #{('dont_align' if @backer.credits)}" } do |form|
          = hidden_field_tag 'project_id', @backer.project.id
          = hidden_field_tag 'backer_id', @backer.id
          = hidden_field_tag 'backer_credits', @backer.credits
          = hidden_field_tag 'payment_method_url', nil
          - unless @backer.credits
            = form.inputs do
              = form.input :full_name, :required => true, :as => :string
              /= form.input :cpf, :as => :string, :input_html => {:autocomplete => 'off'}
              = form.input :email, :required => true, :as => :string
              = form.input :address_street, :as => :string
              = form.input :address_number, :as => :string
              = form.input :address_complement, :required => false, :as => :string
              = form.input :address_neighbourhood, :as => :string
              = form.input :address_zip_code, :as => :string, :input_html => {:autocomplete => 'off'}
              = form.input :address_city, :as => :string
              = form.input :address_state, :as => :select, :collection => State.array
              = form.input :phone_number, :as => :string, :input_html => {:autocomplete => 'off'}
          .submit
            fieldset.accept_terms
              = check_box_tag 'accept'
              = label_tag 'accept', t('accept_terms_html', :link => link_to(t('terms'), terms_path, :target => :_blank)), :class => 'inline'
            - if @backer.credits
              = form.actions do
                .bootstrap-twitter
                  = form.submit (@backer.credits ? t('.submit.credits') : t('.submit.moip')), :disabled => true, :class => 'btn', :id => 'user_submit'

        #payment.hide
          .title
            h1= t('.choose_payment')
            h2= t('.choose_payment_subtitle')  

          .tab_container
            nav#payment_menu
              = link_to '#moip_payment', :id => 'moip', :class => 'selected' , :'data-target' => catarse_moip.review_payment_moip_path(@backer) do
                = t('.choose_boleto') 
              = link_to '#paypal_payment', :id => 'paypal', :'data-target' => catarse_paypal_express.payment_review_paypal_express_path(@backer) do
                = t('.choose_credit_card')
          #paypal_payment.payments_type.hide
          #moip_payment.payments_type.hide
    .clearfix